name = "jiaorong-deepseek-ocr"
family = "deepseek"
release_date = "2026-04-14"
last_updated = "2026-04-28"
attachment = true
reasoning = false
temperature = true
tool_call = false
structured_output = true
open_weights = true

[cost]
input = 0.03
output = 0.03

[limit]
context = 8_192
output = 8_192

[modalities]
input = ["text", "image"]
output = ["text"]
